[tool.commitizen]
name = "cz_conventional_commits"
version = "1.11.0"
update_changelog_on_bump = true
tag_format = "v$version"
version_files = [
    "ezcalour_module/__init__.py:__version__",
    "setup.py:version"
]
